# Generated by Django 5.1.5 on 2026-09-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('source_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('detection_pattern', models.TextField(help_text="Regex (case-insensitive) used to locate this clause's paragraph in the contract text.")),
                ('risk_rules', models.JSONField(default=list, help_text='Ordered list of {pattern, risk, reason, redline}. First regex that matches inside the detected clause wins; evaluated top to bottom.')),
                ('default_risk', models.CharField(default='Low', max_length=20)),
                ('default_reason', models.TextField(blank=True, help_text='Reason used when the clause is detected but no specific risk_rules pattern matches.')),
                ('default_redline', models.TextField(blank=True)),
                ('missing_risk', models.CharField(default='Low', help_text='Risk level to report when this clause category is not found in the contract at all.', max_length=20)),
                ('missing_reason', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk', models.CharField(max_length=20)),
                ('next_action', models.CharField(choices=[('APPROVE', 'Approve'), ('APPROVE_WITH_CONDITIONS', 'Approve with conditions'), ('NEGOTIATE', 'Negotiate'), ('ESCALATE', 'Escalate to legal')], max_length=30)),
                ('summary', models.TextField()),
                ('engine_mode', models.CharField(choices=[('RULE_BASED', 'Rule-based only'), ('LLM_ENHANCED', 'Rule-based + LLM redlines')], max_length=20)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_result', to='reviews.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ClauseFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.SlugField()),
                ('category', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=20)),
                ('is_missing', models.BooleanField(default=False)),
                ('matched_text', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('redline_suggestion', models.TextField(blank=True)),
                ('review_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.reviewresult')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
